[package]
name = "posh-git-rust"
version = "0.4.3"
edition = "2021"
repository = "https://github.com/michalgcc/posh-git-rust/"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.1"